name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy and build infrastructure and site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      working-directory: ./infra
      run: terraform validate -no-color

    - name: Terraform Apply
      id: terraform-apply
      working-directory: ./infra
      run: terraform apply
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.3'

    - name: Build
      run: hugo --minify

    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '.git/*' --follow-symlinks --delete
      env:
        SOURCE_DIR: 'public'
        AWS_REGION: 'eu-west-2'
        AWS_S3_BUCKET: ${{ steps.terraform-apply.outputs.portfolio_s3_bucket_name }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

